### ISSUE TITLE
Call to undefined method Drupal\Core\Entity\EntityDefinitionUpdateManager::applyUpdates

### ISSUE THREAD

**Issue by socialnicheguru** [omega8cc/drush#6]
Call to undefined method Drupal\Core\Entity\EntityDefinitionUpdateManager::applyUpdates() in[error]
drush_update_entity_definitions() (line 326 of
/usr/local/share/boa-drush/commands/core/drupal/update_10.inc) #0
/usr/local/share/boa-drush/commands/core/drupal/batch_10.inc(178):
drush_update_entity_definitions()
#1 /usr/local/share/boa-drush/commands/core/drupal/batch_10.inc(124): _drush_batch_worker()
#2 /usr/local/share/boa-drush/includes/batch.inc(99): _drush_batch_command()
#3 /usr/local/share/boa-drush/commands/core/drupal/update_10.inc(245): drush_batch_command()
#4 /usr/local/share/boa-drush/commands/core/core.drush.inc(1246): _update_batch_command()
#5 /usr/local/share/boa-drush/includes/command.inc(422): drush_core_updatedb_batch_process()
#6 /usr/local/share/boa-drush/includes/command.inc(231): _drush_invoke_hooks()
#7 /usr/local/share/boa-drush/includes/command.inc(199): drush_command()
#8 /usr/local/share/boa-drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch()
#9 /usr/local/share/boa-drush/includes/preflight.inc(67):
Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#10 /usr/local/share/boa-drush/drush.php(12): drush_main()
#11 {main}.

function is deprecated:
https://www.drupal.org/node/3034742
https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Entity%21EntityDefinitionUpdateManager.php/function/EntityDefinitionUpdateManager%3A%3AapplyUpdates/8.9.x
https://github.com/hechoendrupal/drupal-console/issues/4326

**Comment by omega8cc** [comment]
Entity updates are disabled by default, unless explicitly enabled:


```php
  $items['updatedb'] = array(
    'description' => 'Apply any database updates required (as with running update.php).',
    'bootstrap' => DRUSH_BOOTSTRAP_DRUPAL_SITE,
    'global-options' => array(
      'cache-clear',
    ),
    'options' => array(
      'entity-updates' => 'Run automatic entity schema updates at the end of any update hooks. Defaults to --no-entity-updates.',
    ),
    'aliases' => array('updb'),
  );

```

```php
  if (drush_get_option('entity-updates', FALSE) &&  \Drupal::entityDefinitionUpdateManager()->needsUpdates()) {
    $operations[] = array('drush_update_entity_definitions', array());
  }

```

**Comment by omega8cc** [comment]
Furthermore, in BOA we no longer use Drush 8 to perform db schema updates in Drupal 8+ because we support and invoke site-local Drush transparently.

Please check for reference:

https://github.com/omega8cc/boa/blob/5.x-dev/CHANGELOG.txt#L214

https://github.com/omega8cc/boa/blob/5.x-dev/docs/DRUSH-CLI.md#drush-management-in-boa
